AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for lambda-vpc

Parameters:
  SecurityGroupIds:
    Type: CommaDelimitedList
    Default: sg-0651d8f4f91c49ee3
  SubnetIDs:
    Type: CommaDelimitedList
    Description: The list of SubnetIDs in your Virtual Private Cloud (VPC)
    Default: subnet-0d6f727dcf302d96c,subnet-0cdb608d489c054bb,subnet-09454883ec1f70867
  EFSpath:
    Type: String
    Default: /mnt/efs
  AccessPointARN:
    Type: String
    Description: Access point ARN
    Default: arn:aws:elasticfilesystem:ap-south-1:960351580303:access-point/fsap-02e34b7865aaef035

Resources:
  SandyCustomImage:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./custom-image
      DockerTag: sandy-efs-test
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 900
      MemorySize: 1024
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIDs
      FileSystemConfigs:
        - Arn: !Ref AccessPointARN
          LocalMountPath: !Ref EFSpath
      Policies:
        - Statement:
            - Sid: Admin
              Effect: Allow
              Action: "*"
              Resource: "*"
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Timeout: 3
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIDs
      FileSystemConfigs:
        - Arn: !Ref AccessPointARN
          LocalMountPath: !Ref EFSpath
      Policies:
        - Statement:
            - Sid: Admin
              Effect: Allow
              Action: "*"
              Resource: "*"

  Lambda1:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambda-1
      DockerTag: sandy-lambda-1
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 900
      MemorySize: 1024
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIDs
      FileSystemConfigs:
        - Arn: !Ref AccessPointARN
          LocalMountPath: !Ref EFSpath
      Policies:
        - Statement:
            - Sid: Admin
              Effect: Allow
              Action: "*"
              Resource: "*"
  Lambda2:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambda-2
      DockerTag: sandy-lambda-2
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 900
      MemorySize: 1024
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIDs
      FileSystemConfigs:
        - Arn: !Ref AccessPointARN
          LocalMountPath: !Ref EFSpath
      Policies:
        - Statement:
            - Sid: Admin
              Effect: Allow
              Action: "*"
              Resource: "*"
  Lambda3:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambda-3
      DockerTag: sandy-lambda-3
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 900
      MemorySize: 1024
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIDs
      FileSystemConfigs:
        - Arn: !Ref AccessPointARN
          LocalMountPath: !Ref EFSpath
      Policies:
        - Statement:
            - Sid: Admin
              Effect: Allow
              Action: "*"
              Resource: "*"
  Lambda4:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambda-4
      DockerTag: sandy-lambda-4
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 600
      MemorySize: 2048
      EphemeralStorage:
        Size: 2048
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIDs
      FileSystemConfigs:
        - Arn: !Ref AccessPointARN
          LocalMountPath: !Ref EFSpath
      Policies:
        - Statement:
            - Sid: Admin
              Effect: Allow
              Action: "*"
              Resource: "*"

  Lambda7:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambda-7
      DockerTag: sandy-lambda-7
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 60
      MemorySize: 2048
      EphemeralStorage:
        Size: 2048
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIDs
      FileSystemConfigs:
        - Arn: !Ref AccessPointARN
          LocalMountPath: !Ref EFSpath
      Policies:
        - Statement:
            - Sid: Admin
              Effect: Allow
              Action: "*"
              Resource: "*"

  StepFunction1Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  StepFunction1:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: step-function/stpfn.asl.json
      Role: !GetAtt StepFunction1Role.Arn
      Tracing:
        Enabled: true
      DefinitionSubstitutions:
        Lambda1Arn: !GetAtt Lambda1.Arn
        Lambda2Arn: !GetAtt Lambda2.Arn
        Lambda3Arn: !GetAtt Lambda3.Arn
        Lambda4Arn: !GetAtt Lambda4.Arn
