version = 0.1
[default.deploy.parameters]
stack_name = "sandy-efs-setup-part1"
resolve_s3 = true
s3_prefix = "sandy-efs-setup-part1"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
