version = 0.1
[default.deploy.parameters]
stack_name = "k3d-docker-images-build"
resolve_s3 = true
s3_prefix = "k3d-docker-images-build"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
