AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  jfrog-poc

  Sample SAM Template for jfrog-poc

Resources:
  GitCILambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 900
      MemorySize: 1024
      Environment:
        Variables:
          GITHUB_URL: https://github.com/sandykumar93/ACD-Serverless-Leave-Approval.git
          STACK_NAME: rahul-acd-test1
          REGION: us-east-1
          BUCKET_NAME: rahul-acd-test1
          COGNITO_USER_POOL_DOMAIN: rahul-acd2

      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:*
                - s3:*
                - iam:*
                - logs:*
                - cloudfront:*
                - lambda:*
                - states:*
                - cognito-idp:*
                - cognito-sync:*
                - cognito-identity:*
                - execute-api:*
                - apigateway:*
                - cloudformation:*
                - cloudwatch:*
              Resource: "*"

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: functions/git-ci-lambda-function
      DockerTag: custom-ci
